# -*- coding: utf-8 -*-
"""test.ipynp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ireKftI79qlivg8m8q1ZyAgcO8F4PyHW
"""

from algorithms import *

deuJoz.sim(3, "b") #Simulates a three bit number and a balanced function using the qasm_simulator

deuJoz.run(3,"b", device='ibmq_16_melbourne', plotTool='mpl', shots=1000) #Runs the algorithm above but on the ibmq_16_mealbourne quantum computer with 1000 shots

berVaz.sim('10011') #Runs the Bernstein-Vazarani algorithm on input '1011' using the qasm_simulator

berVaz.run('1001', device='ibmq_16_mealbourne') #Runs the Bernstein Vazarani algorithm for the number '1001' on the ibmq_16_mealbourne quantum computer.